### ISSUE TITLE
Bug: The modal-body is empty

### ISSUE THREAD

**Issue by ilvacca** [grocy/grocy#2480]
Hello everyone, I recently installed Grocy in my mini pc (a Beelink with an Intel N95 cpu and Debian) by using [this ](https://github.com/linuxserver/docker-grocy#docker-compose-recommended-click-here-for-more-info) docker-compose command (with the proper path obviously).

Unfortunately, using Grocy, I realized that every modal-body appearing on the screen (when adding for example a Location, image attached) is always empty. To make things appear inside the modal I have to resize the window.

In the console I get the following message from the browser:

 *"[Deprecation] Listener added for a synchronous 'DOMSubtreeModified' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead."*

Is it related with the problem?

Why this happens?
Thank you

![image](https://github.com/grocy/grocy/assets/24767215/1504eb92-95c6-4108-b5b9-df8b2c308918)

**Comment by berrnd** [comment]
What's the problem about searching a little tiny bit beforehand?

Duplicate of #2421 (and #2453, and #2454, and #2476). Use the current release v4.1.0 and triple check you did what's needed to be done after an upgrade to eliminate caching problems and this won't be a problem anymore.

&nbsp;
> Is it related with the problem?

Of course not.

**Comment by ilvacca** [comment]
I would search with pleasure if I knew what to look for. If I knew the problem I probably would have solved it without asking someone for help. I think that is why people have difficulty "searching a little tiny bit beforehand".

In any case, I still haven't been able to solve the problem. I changed browsers, emptied the "data/viewcache" folder but nothing.

Also I can add that:

- I tried with 3 different browsers: Chrome, Brave (probably Chrome based) and Edge (I never use this one, I just set it up and on the first visit I already have the problem).
- mine is a fresh new installation (so 4.1.0) and not from an "update".

I remind you that I installed Grocy through [this](https://github.com/linuxserver/docker-grocy#docker-compose-recommended-click-here-for-more-info), so I completely skipped the "How to install" and "How to upgrade" sections.

If you want to help me fine. If not, I'll get over it.
Anyway, thank you for the work you have done in these years.

**Comment by berrnd** [comment]
> I would search with pleasure if I knew what to look for.

Using the title of your created bug report here (the single word "modal" would be even enough) would exactly give the duplicates I've mentioned. The excuses people have for not searching are pure entertainment.

&nbsp;
> I remind you that I installed Grocy through [this](https://github.com/linuxserver/docker-grocy#docker-compose-recommended-click-here-for-more-info)

I don't care (and no need to remind me, I read stuff I answer on) and don't maintain any community contributed third party tools/integrations/whatever.

&nbsp;
> so I completely skipped the "How to install" and "How to upgrade" sections.

Skipping READMEs is always a good thing.

&nbsp;
> If you want to help me fine. If not, I'll get over it.

I can't do anything without having a fully reproducible example (I'm not a magician who can guess all the details), that was also mentioned on the issue template you most likely also skipped. So unless having that, I guess the later is the way to go. Just also a reminder: If it works on the official demo instances (I have no doubts you've tested that, since that's just another thing mentioned on the issue template) and not on your personal one, it can't be a bug.

**Comment by berrnd** [comment]
Based on the few details provided here, I've invested half an hour testing this focused on the [/location page](https://demo-prerelease.grocy.info/locations) and Chrome based Browsers.

I got this sporadically, not really reproducible and presume a problem on their side. However, I can't change the big players, so of course I've tried to add a workaround (in 11ac985e57a4481191e4dc44ee1fe6e913d773e8) - if you want to test it: Replace the file `public/js/grocy.js` by [that one](https://raw.githubusercontent.com/grocy/grocy/11ac985e57a4481191e4dc44ee1fe6e913d773e8/public/js/grocy.js) (and ensure client side / Browser caches are cleared after doing that).

**Comment by ilvacca** [comment]
The bug has been fixed and now it seems to work. Thank you.

**Comment by jstrot** [comment]
I'm still experiencing this with latest Git master (e01e0f3abe85945f8fac3ee2117dcbeb4a4e90aa) running Chrome stable (122.0.6261.111). I wiped the data/viewcache directory but it doesn't help: Every time I add a new item I need to resize my browser window to force the dialog to display more than its Close button. Same goes for adding under Products, Locations, ...

This is a fresh install for me so the initial experience is pretty awful. (Started with v4.1.0 and moved to Git master due to this bug)

I'm happy to be your guinea pig... I will study your previous fixes and see if I can make it work on my end too.

**Comment by jstrot** [comment]
> I'm still experiencing this with latest Git master (e01e0f3)...

After some debugging, I found the css in the browser didn't match the css on file: I had to clear my browser cache to make it work!

Would be nice to have development versions use the SHA or something instead of the previous release tag in URLs (e.g., `grocy.css?v=e01e0f3` instead of `grocy.css?v=4.1.0`)

Anyway. Sorry for the noise.

**Comment by berrnd** [comment]
> moved to Git master

Then make 110 % sure that you know you can handle everything needed (database migrations and so on are only meant to work between releases, not between every commit, [README ref](https://github.com/grocy/grocy?tab=readme-ov-file#database-migrations)) and don't report anything which will maybe cause problems due to that here in the future.

&nbsp;
> Would be nice to have development versions use the SHA or something

That's already the case, simply check the [pre-release demo](https://demo-prerelease.grocy.info/) ([config option ref](https://github.com/grocy/grocy/blob/e01e0f3abe85945f8fac3ee2117dcbeb4a4e90aa/config-dist.php#L16-L20)) where exactly that is live since years.

&nbsp;
In any case, all that is off-topic here.
